plugins {
    id 'com.android.application'
}

android {
    namespace 'com.endroid.screenoff'
    compileSdk 34

    defaultConfig {
        applicationId "com.endroid.screenoff"
        minSdk 28
        targetSdk 34
        versionCode 10
        versionName "1.4.0"
        resourceConfigurations += ['en']
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    signingConfigs {
        debugLocal {
            storeFile file("${System.properties['user.home']}/.android/debug.keystore")
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debugLocal
        }
    }
}

dependencies {
    implementation 'com.google.android.material:material:1.12.0'
}
