-keep class com.endroid.screenoff.service.LockAccessibilityService { *; }
-keep class com.endroid.screenoff.service.LockTileService { *; }
-keep class com.endroid.screenoff.ui.LockActivity { *; }
-keep class com.endroid.screenoff.ui.SetupActivity { *; }
-keep class com.endroid.screenoff.util.** { *; }
-keepattributes SourceFile,LineNumberTable
