-keep class com.endroid.screenoff.LockAccessibilityService { *; }
-keep class com.endroid.screenoff.LockTileService { *; }
-keep class com.endroid.screenoff.LockActivity { *; }
-keep class com.endroid.screenoff.SetupActivity { *; }
-keep class com.endroid.screenoff.AppServiceHolder { *; }
-keep class com.endroid.screenoff.LockHelper { *; }
-keepattributes SourceFile,LineNumberTable
-dontwarn androidx.**
-dontwarn com.google.android.material.**
